name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 1 * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Get current minor version
      id: minor-version
      run: echo "::set-output name=version::$((${{ github.run_number }}-1))"
      
    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64, linux/arm64
        push: true
        tags: flexibletoast/tvcleanup:1.${{ steps.minor-version.outputs.version }}, flexibletoast/tvcleanup:latest

    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: flexibletoast/tvcleanup
